- session10/01python.md
- session10/02collaboration.md
- session10/03testing.md
- session10/04libraries.md
- session10/05construction.md
- session10/06design.md
- session10/07dry.md
- session10/08performance.md
- session10/09furthergit.md
- session10/slides.md
Add carriage return after title to fix rendering issue.
> add whitespace, fix rendering

- session03/01primer.md
- session03/02HowToTest.md
- session03/05nose_exercise.md
- session03/08Methodology.md
- session04/01libraries.md
- session05/02comments.md
- session05/04refactoring.md
Hi RSD team,
I have tidied up a few minor typos in the lessons. Please could you check the changes and merge if you are happy? These are my first set of edits, so this is just a trial run for later changes really...
Thanks,
Tom
> fixed a few typos

- ch02git/06ForkAndPull.ipynb
From https://github.com/UCL-RITS/research-software-development/issues/286
I might add a web sequence diagram if you think it's useful @jamespjh
> Notes for the Fork and Pull model requested in #286 ready to review.

- session99/linux.md
- session99/mac.md
- session99/windows.md
I've not tested the windows or mac steps. I'm not sure how VS code integrates with the rest, but I've added a couple of links for that.
Fixes #124. Fixes #125.
> Update installation steps for different OSs

- ch07dry/025Iterators.ipynb
- requirements.txt
Will fix #115.
~Still need to look at the decorator material~ Now done.
Also, the beginning of the iterator section might need some reworking: the fact that we save memory from using a range (vs a list) isn't directly related with it using an iterator, so we should probably rephrase that so it's not misleading.
> Week09 iterators

- ch07dry/040Exceptions.ipynb
Fixes #116.
No big changes, most of the diff is from rerunning the notebook to reset the numbering.
> Week09 exceptions

- index.md
- session99/index.md
- session99/linux.md
- session99/mac.md
- session99/windows.md
Quick one fixing the installation instructions
> Updates to setup instructions

- ch03tests/01testingbasics.ipynb
- requirements.txt
> Introduction to testing chapter

- ch01data/061internet.ipynb
- ch01data/064JsonYamlXML.ipynb
- ch01data/070hdf5.ipynb
A couple of typos or similar I found when reading through the data lesson.
> fix some typos

- requirements.txt
See #186 (temporary workaround).
> Temporarily downgrade nbconvert to fix build

- Makefile
It seems Inkscape has a problem when called from the command line
https://gitlab.com/inkscape/inkscape/-/issues/294
> 🐛 Work around attempt to Inkscape problem

- README.md
Updates the `README` with info about how the course is structure and the steps to build the lessons locally using the same method than the gh-actions (thanks to `act`!)
Fixes #48
> Contributing and building info

- _config.yml
- ch00python/010exemplar.ipynb
- requirements.txt
I couldn't find a better link for the "Partner with us" page, but I don't think it's actually displayed anywhere anyway.
> Update for move to ARC and CS

- .github/workflows/build_site.yml
All the git examples that connect with GH are throwing error. This should fix them
> Adds SSH keys to work with other repositories

- ch02git/01Intro.ipynb
- ch02git/04Publishing.ipynb
- ch02git/05Collaboration.ipynb
- ch02git/06ForkAndPull.ipynb
- ch02git/10Branches.ipynb
- ch02git/11Miscellany.ipynb
- ch02git/12Remotes.ipynb
- ch02git/13Rebase.ipynb
- ch02git/14Bisect.ipynb
- changes `master` to `main` (also defines as a default at the start of the lesson)
- Uses `switch` instead of `checkout`
- Sets default pull action when different stories to create a merge commit
- Adds more information when talking about naming branches.
> Sets merge commit as default when pulling, and other branching changes

- ch04packaging/05Process.ipynb
Requires a login I don't have at least?
Replace with link to pdf on UNC website.
> Fix broken link

- ch04packaging/07Licensing.ipynb.py
Closes #209
https://github.com/UCL/rsd-engineeringcourse/pull/241#issuecomment-2284128232 for failing tests
> chore: add EC's JLA for choosing a license

- session99/linux.md
- session99/mac.md
> fix (installation): working links + canopy is at EOL

- ch04packaging/07Licensing.ipynb.py
> Add a line for REUSE in licensing

- ch04packaging/03Packaging.ipynb.py
Simple update to make the explanation on the notes cleaner
Same as #261 but from within to allow the action to run.
> Cleans up the tree and fixes doctest ImportError

- session99/index.md
> Fix eduroam
