session99/mac.md

This is for the link to good editors in the Mac set-up. Although the link is clickable in the Github version, when I look at the released version of the pages it isn't.

Making a link i Mac set-up instructions live

---

ch01data/070hdf5.ipynb

New notebooks (#160) need additional metadata, or they won't be included in the deployed pages...

Show new HDF5 page in deployed site

---

ch08performance/040cython.ipynb

It should render all properly now.

Removes blank space that makes cython magic load to fail

---

ch05construction/09patterns.ipynb

Link to Strategy Pattern section was previously not working.

Fix link and make section headings consistent

---

index.md

I thought about changing the URL to point to the new i4Health CDT, but decided against this, as its not really relevant. People are now registering from all over college.  Students would be expected to find the module in the UCL Module Catalogue, or by reputation within their department. So, the link itself is unnecessary.

Issue #184: Remove links to obsolete CDT Medical Imaging website.

---

Makefile
index.md

The PDF was breaking the Travis build and needs investigation.
The zip containing the notebooks is not linked from anywhere, can be retrieved from GitHub and is taking up a lot of space.
Stop them temporarily, at least.

Pause building PDF and zipping notebooks

---

ch00python/010exemplar.ipynb

Metadata accidentally removed in #183, which excluded it from the Jekyll pages!

Include greenpath notebook on website again

---

ch04packaging/04documentation.ipynb

Added some clarifications including where to go to install Sphinx from, as well as updated a broken link to `sphinx-quickstart` documentation.

Review docs notes

---

ch02git/14Bisect.ipynb

Also updated the example to used repository at ucl-rits
I've also updated the output of some cells as to keep it consistent with what we expect now.
I'd prefer to get the errors in red, but then they are after the stdout... which
makes it harder to understand what's going on.

Updates git bisect instructions to make them more readable

---

.github/workflows/build_site.yml
Gemfile
Makefile
README.md
_config.yml

- Updates Jekyll to the latest version.
- Uses now kramdown as the markdown converter.
- This includes changes on how we manage the theme (via remote-themes) that at the moment points to my fork - till I'm sure we can push these changes on the theme itself.

jekyll's updates

---

ch01data/062csv.ipynb

The csv module section had been removed due to problems with the data
downloaded. This has now been fixed on our other course notes. The content has
been almost moved through, but leaving a section about how to read the data with
Numpy.
Additionally, the section has been expanded to include a very short introduction
to pandas.

Updates the csv section from the doctoral skills and adds pandas

---

ch00python/023types.ipynb

Changes made:
* Remove examples and discussion of Python 2 from `ch00python/023types.ipynb`
* Change discussion about how the behaviour of operators depends on the types of the operands
- Previously the discussion was around the Python 2 behaviour of the division operator
- Now the example is of the addition operator applied to `int`s vs `float`s
* Mention that division always returns a float. To perform integer division the `divmod` function can be used
* Added note about always using at least one digit after a decimal point to improve readability

Remove mention/use of Python 2 from discussion about types

---

ch04packaging/03Packaging.ipynb.py

Closes #234 |
Updates the week 7 notes on packaging to use `pyproject.toml` rather than `setup.py`. 
Assumes that notebooks are still running on the original directory structure. Also throws in a mention that some major packages might not have switched from `setup.py` to `pyproject.toml`: in which case students should see some similarities between the two formats and fields used in each.

Convert packaging lesson to use pyproject.toml instead

---

ch04packaging/03Packaging.ipynb.py

`setuptools_scm` needs that the package is in a git repository. The way the notes are built locally diverges, somehow, of when it's built on gh actions. Locally, I believe it detects this repository, whereas on gh actions somehow it doesn't and it fails.
Decided to comment out that line with a comment saying to use it when in a git repository.

Fixes building sample repository without being on a git repository

---

ch03tests/06Debugger.ipynb.py

Markdown for the `pdb` entry is not rendering the link.

Fixes md formatting - debugging lesson

---

.github/workflows/build_site.yml

The new deployment workflow did not work as expected - https://github.com/UCL/rsd-engineeringcourse/actions/runs/10389062533 💀 
This PR fixes it. Passing workflow on my fork - https://github.com/Saransh-cpp/rsd-engineeringcourse/actions/runs/10389554321. Deployed website on my fork - https://saransh-cpp.github.io/rsd-engineeringcourse/.

fix: split deployment job and give it write permission

---

ch04packaging/03Packaging.ipynb.py

The deployed page throw an error (although I did not get the error locally when I was writing the page, weird) - https://github-pages.ucl.ac.uk/rsd-engineeringcourse/ch04packaging/03Packaging.html

fix: hatch requires extra config if __init__.py is not present

---

ch08performance/030misc-libs.ipynb.py
requirements.txt

Closes #239 
I will need some help here to filter what content is underexplained and what is overexplained 🙂

feat: add a page about compiling + parallel and GPU computing

---

.github/python/requirements.txt

This adds the dependency that complains it doesn't exists when trying to use it. Before python 3.12 distutils was part of python, not anymore ([PEP632](https://peps.python.org/pep-0632/)).

Cython examples are not showing

---

ch05construction/02conventions.ipynb.py

This PR updates the naming conventions section to promote the use of `underscore_separation` for function names, in alignment with [[PEP 8](https://pep8.org/)](https://pep8.org/) guidelines.
Fixes issue: [[UCL/rsd-engineeringcourse#263](https://github.com/UCL/rsd-engineeringcourse/issues/263)](https://github.com/UCL/rsd-engineeringcourse/issues/263)

style: Advertise underscore_separation for function names
